name: MobArenaPlugin
main: com.nordryd.mobarena
version: 1.0
api-version: 1.15
commands:
  marena:
    description: Base for all MobArenaPlugin commands.
    permission: marena.user
permissions:
  marena.admin:
    description: Gives access to all commands.
    default: op
    children:
      marena.user: true
  marena.user:
    description: Gives access to commands that do not enable grieving.
